# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('SPL', 'School Pupil Leader'), ('ASPL', 'Assistant School Pupil Leader')], default='ASPL', max_length=4),
            preserve_default=False,
        ),
    ]
