# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_candidate_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='category',
        ),
    ]
