# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_candidate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('SPL', 'School Pupil Leader'), ('ASPL', 'Assistant School Pupil Leader')], default='SPL', max_length=4),
        ),
    ]
