# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_candidate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(default='assets/none.jpg', upload_to='assets/'),
        ),
    ]
