# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(default='assests/none.jpg', upload_to='assets/'),
        ),
    ]
